export const EDGE_CONFIG = {
  combinedModelWeight: 0.65,
  combinedConsensusWeight: 0.35,
  maxConsensusDelta: 3,
  maxMoneylineConsensusDelta: 0.08,
  maxEdgeForScore: 4,
  maxMoneylineEdgeForScore: 0.1,
  significantSpreadOrTotalMove: 1.5,
  significantPropMove: 2,
  stalePenalty: 0.75,
  spreadTolerance: 1,
  totalTolerance: 1,
  propTolerance: 0.5,
  spreadHalfPointPenalty: 0.35,
  spreadFullPointPenalty: 0.75,
  totalHalfPointPenalty: 0.25,
  totalFullPointPenalty: 0.5,
  propHalfPointPenalty: 0.4,
} as const;
